# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

build_snn_graph <- function(neighbors, scheme) {
    .Call('_bluster_build_snn_graph', PACKAGE = 'bluster', neighbors, scheme)
}

sum_neighbor_weights <- function(nclusters, neighbors, clusters, weights) {
    .Call('_bluster_sum_neighbor_weights', PACKAGE = 'bluster', nclusters, neighbors, clusters, weights)
}

